// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCinoCBUM9qtoebC4X_pTY8zeVeA58AlSc',
    appId: '1:367468793802:web:076fd1a7e1fafb12260933',
    messagingSenderId: '367468793802',
    projectId: 'test-1234-f0d36',
    authDomain: 'test-1234-f0d36.firebaseapp.com',
    databaseURL: 'https://test-1234-f0d36-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-1234-f0d36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgoEhL9UC19GSyRo6UfgWaz0-5sTVzxpM',
    appId: '1:367468793802:android:58db2bec1dc30801260933',
    messagingSenderId: '367468793802',
    projectId: 'test-1234-f0d36',
    databaseURL: 'https://test-1234-f0d36-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-1234-f0d36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF6AzahNlbUxOxKj8xuAu5IuuxjAd57zE',
    appId: '1:367468793802:ios:579d9a598f5f677b260933',
    messagingSenderId: '367468793802',
    projectId: 'test-1234-f0d36',
    databaseURL: 'https://test-1234-f0d36-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-1234-f0d36.firebasestorage.app',
    iosBundleId: 'com.example.exeAssignment',
  );

}