// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCncOpMrD0iVKLfhGO2qkqPAcCxr0XeOqs',
    appId: '1:395362193833:web:6ed99bbf57b161561134b8',
    messagingSenderId: '395362193833',
    projectId: 'defects-capturing-app',
    authDomain: 'defects-capturing-app.firebaseapp.com',
    storageBucket: 'defects-capturing-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1j2KLa-rYaq2rnb-hhJevmnkzEsVb_jk',
    appId: '1:395362193833:android:c49dffcfd696f50f1134b8',
    messagingSenderId: '395362193833',
    projectId: 'defects-capturing-app',
    storageBucket: 'defects-capturing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHEYFHKKYQUbMYFhXNcx0TmDjazkOlhSw',
    appId: '1:395362193833:ios:8507bfc95a3a34e01134b8',
    messagingSenderId: '395362193833',
    projectId: 'defects-capturing-app',
    storageBucket: 'defects-capturing-app.firebasestorage.app',
    iosBundleId: 'com.example.exeAssignment',
  );
}
